version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestP8Project
  gitServerName: rlakshitha0912
  gitUrl: https://github.com/rlakshitha0912/TestP8Project
  gitUsername: rlakshitha0912
  gitBranch: main
